// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSp97Y10Ray_4JbAAQWbFL1kOoxsmXMGk',
    appId: '1:1034073583808:web:8e3dbe16be4be19d553d25',
    messagingSenderId: '1034073583808',
    projectId: 'testingcli-51ca4',
    authDomain: 'testingcli-51ca4.firebaseapp.com',
    storageBucket: 'testingcli-51ca4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhSjWBQcgbkOIT8KenvCBsJd_l-1YabWU',
    appId: '1:1034073583808:android:f390ca775f5e3dc2553d25',
    messagingSenderId: '1034073583808',
    projectId: 'testingcli-51ca4',
    storageBucket: 'testingcli-51ca4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1D2MfQsLyORoLAovhQ_ppdmO9xfX71oE',
    appId: '1:1034073583808:ios:5ab5b29d1590dbb7553d25',
    messagingSenderId: '1034073583808',
    projectId: 'testingcli-51ca4',
    storageBucket: 'testingcli-51ca4.appspot.com',
    iosBundleId: 'com.techwaji.firebaseCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1D2MfQsLyORoLAovhQ_ppdmO9xfX71oE',
    appId: '1:1034073583808:ios:1a253725f14348be553d25',
    messagingSenderId: '1034073583808',
    projectId: 'testingcli-51ca4',
    storageBucket: 'testingcli-51ca4.appspot.com',
    iosBundleId: 'com.techwaji.firebaseCli.RunnerTests',
  );
}
